disabled_rules:
- line_length
- trailing_whitespace
- orphaned_doc_comment
- nesting
- function_body_length
included:
excluded:
- Pods
- Mohaeng/Sources/AppDelegate.swift
- Mohaeng/Sources/SceneDelegate.swift

identifier_name:
  excluded:
    - id
